server:
  port: 8081

spring:
  session:
    store-type: none
#security:
#  basic:
#    enabled: false # 是否开启

power:
  security:
    browser:
#      loginPage: /demo_signIn.html
      #      loginType: REDIRECT
      loginType: JSON
    code:
      image:
        length: 6 # 验证码长度
        width: 100
        url: /user/*
