server:
  port: 8081

spring:
  session:
    store-type: none
#security:
#  basic:
#    enabled: false # 是否开启

power:
  security:
    browser:
#      loginPage: /demo_signIn.html
      loginType: REDIRECT
#      loginType: JSON
